---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    reviewers:
      - "andros21"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/Rome"
    rebase-strategy: "disabled"
    reviewers:
      - "andros21"
