---
name: CD

"on":
  push:
    tags:
      - "[0-9].[0-9].[0-9]+"

permissions:
  contents: write

jobs:
  changelog:
    name: add changelog
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 0
      - name: get tag
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF:10}" >> "$GITHUB_ENV"
      - name: refresh changelog
        uses: orhun/git-cliff-action@72048666575e88745b71a3e9ded1bb17b2923804
        with:
          config: cliff.toml
          args: --verbose --tag ${{ env.TAG }}
        env:
          OUTPUT: CHANGELOG.md
      - name: commit changelog
        uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081
        with:
          message: "chore(CHANGELOG): add imagine ${{ env.TAG }} changes"
          add: 'CHANGELOG.md'
          new_branch: master
