---
name: CD

"on":
  push:
    tags:
      - "[0-9].[0-9].[0-9]+"

permissions:
  contents: write

jobs:
  changelog:
    name: add changelog
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - name: get tag
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF:10}" >> "$GITHUB_ENV"
      - name: refresh changelog
        uses: orhun/git-cliff-action@14bb67385aaac969efa2f146d137a42bb3b0aa87
        with:
          config: cliff.toml
          args: --verbose --tag ${{ env.TAG }}
        env:
          OUTPUT: CHANGELOG.md
      - name: commit changelog
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
        with:
          message: "chore(CHANGELOG): add imagine ${{ env.TAG }} changes"
          add: 'CHANGELOG.md'
          new_branch: master
